spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotelManagementSystem
    username: 
    password: 
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
